### PR TITLE
mycopy_TinyG

### PR DESCRIPTION
**Pull request by slootmat**

### CODE REVIEW

**Comment by justinclift** [comment]
@slootmat Guessing this was an accidental button press? :wink:

**Comment by slootmat** [comment]
Yes, sorry. not pursuing a pull.
Best,
Slootmat

**Comment by justinclift** [comment]
No worries @slootmat. :smile:

**Comment by slootmat** [comment]
Hi Justin,
I'm looking at the DDA interrupt in the master branch, and am a bit
puzzled over the way the accumulators track each motor's participation in
the segment.

====================================================
namespace Motate {            // Must define timer interrupts inside the
Motate namespace
template<>
void dda_timer_type::interrupt()
{
.
.
.
    // process DDAs for each motor
    if  ((st_run.mot[MOTOR_1].substep_accumulator +=
st_run.mot[MOTOR_1].substep_increment) > 0) {
        motor_1.stepStart();        // turn step bit on
        st_run.mot[MOTOR_1].substep_accumulator -=
st_run.dda_ticks_X_substeps;
        INCREMENT_ENCODER(MOTOR_1);
    }
.
.
.
     // Process end of segment.
    // One more interrupt will occur to turn of any pulses set in this pass.
    if (--st_run.dda_ticks_downcount == 0) {
        _load_move();       // load the next move at the current interrupt
level
    }
}
========================================================
I understand from the comments in  function stat_t st_prep_line(float
travel_steps[], float following_error[], float segment_time) that
 "ticks_X_substeps is the maximum depth of the DDA accumulator (as a
negative number)"  That comment alone would give me the impression that the
accumulator would be initially assigned that value as a negative number,
just once, at the beginning of the segment, and that the respective motor's
"substep_increment" would successively be added to that, on each entry to
the interrupt. I recognize that in the general case, the accumulator could
be carrying over unused steps from prior segments. However, I still don't
understand why the full value of "st_run.dda_ticks_X_substeps" is
re-applied to the accumulator.

Would you be able to provide some explanation/documentation, say a simple
use case on how the dda interrupt's accumulator actually counts its way to
zero for each respective participating motors' designated step count?

Kind regards,

Sam (aka Slootmat)

Firmware Engineer
Bantam Tools

**Comment by giseburt** [comment]
Hi Sam,

I'l take a stab at this. This is something that took me a while to get right in my mind as well, but it turns out to be simpler than it seems from the code, mostly because we are doing this as integer instead of floating/fixed point (for obvious mechanical reasons).

One thing that may help is that in newer code we have replaced st_run.dda_ticks_X_substeps with DDA_SUBSTEPS (what it was set to) in this area to be more clear that it's a constant. (There's a minor optimization gain as well.)

Instead of integer numbers, let's say they are floating point, and we're saying one step is accumulated from 0.0 to 1.0.

In which care the code reads roughly like:

// process DDAs for each motor
accumulator[motor] += increment[motor];
if (accumulator[motor] > 1.0) {
  // turn step bit on
  accumulator[motor] -= 1.0;
  // track this with a virtual encoder
}

That ensures that whatever portion of a step we go past is retained in the accumulator. Based on the fact that we know the DDA timer period and the relative timing of the other motors, we set the increment accordingly, and each increment must be < 1.0.

As an optimization we handle the entire thing in negative so that the if statement is detecting a transition of - to +. Only the if statement changes for this, however.  This may no longer be needed for ARM processors and modern compilers, but we haven't done the analysis to determine for sure, so we leave it.

Now we can't really do this reliably in floating point, so we need to convert this to integer. For safety we allow some room in the accumulator to go negative without overflow, so we scale the 1.0 value to (INT64_MAX-100), and the increment is scaled by the same amount (meaning it is always less than that.)

This yields this pseudocode:

accumulator[motor] += increment[motor];
if (accumulator[motor] > 0) {
  // turn step bit on
  accumulator[motor] -= DDA_SUBSTEPS;
  // track this with a virtual encoder
}

Does that help?

-Rob

**Comment by slootmat** [comment]
Hi Rob,

Thank you for your prompt reply! Yes, that not only helps, but alters my
understanding quit a bit.

Please confirm or correct my new understanding in the following simplified
terms:

1. The step_increment is the means by which a given motor's fractional
distance in a segment is scaled to spread out it's activity across the
entire lifetime of the segment.
   a. So, say if it's length is one half the full segment length, then the
step_increment would be 0.5.
   b. Every other pulse/entry into the interrupt would result in that
motor's:
           i.  step pin to get set.
           ii. accumulator' step count to get refreshed with another  -1.0
full step value needing to be counted up to zero, in order for the next
step to be pulsed out to the motor.

2. Substeps in this context are entirely used for scaling a motors's
step_count for the given segment. They are not the same as a motor's
microsteps. However, the motor's step_count is in fact, in units of it's
configured microsteps per step.

If the above is correct, that makes more mechanical sense to have a) all
motors smoothly playing out their lengths across the entire segment
duration, albeit scaled as needed, rather than b) running out their steps,
un-scaled, and abruptly stopping where ever their trajectory ended in the
segment. I am new to the CNC application domain, so my straight-forward
assumption was the latter scenario, b.

Is that about right?

Best,
Sam

**Comment by giseburt** [comment]
Hi Sam,

A little bit of context may help, since you are looking at the inner-most loop of the inner-most subsystem in the whole system:

1. Gcode is translated directly (G0, G1) or indirectly (arcs, homing, etc.) to "blocks," where each block represents an elemental straight line move
2. The blocks are put into the planner, which breaks each move into three "sections" - head (acceleration region), body (cruise region), and tail (deceleration region), all computed to be seamless to the sixth derivative
3. The section curves are then each broken into "segments" - tiny (~1ms) sub-moves that have very few elements: length (in fractional mm), duration (in fractional minutes, IIRC), start velocity, and end velocity
4. These segments are then passed to the kinematics layer for cartesian → motors translation
5. The translated segments are then individually passed (precomputed from mm to microsteps) to the stepper subsystem you were asking about

The step DDA algorithm (derived from the Bresenham algorithm, but heavily modified at this point) takes these parameters computed for each motor and generates the step signals. Note that it's concerned with the step signals at this point, so in this area of the code a "step" is indeed whatever you get out of a step pin pulse, which is often actually a microstep.

Note: I'm looking at newer code than is in edge (but I thought was in edge), so you don't see the linear acceleration code yet. I'll describe it anyway, since it'll be in the code soon enough.

Assuming a segment that starts and ends with the same velocity (which is what the code you see does), then substep_increment is simply substep_increment = round(fabs(travel_steps[motor] * DDA_SUBSTEPS)), where travel_steps[motor] is the (float) steps for this motor to cover during this segment. For the linear acceleration case it gets more complicated, but the concept stays the same, with he addition of an increment to the increment for each DDA tick.

Overall the DDA interrupt looks like:

* Unconditionally unset all step pins (faster to just do it then branch)
* exit if we're done with or don't have a segment (downcount is 0)
* accumulate and possibly step each motor's step pin
* (linear acceleration) accumulate each motor's accumulator accumulator
* downcourt -= 1
* if we're done with this segment (downcount == 0) request loading of the next segment into the st_run structure (_load_move())


This scheme provides smoothly playing out all of the steps of each motor in a synchronized manner at the ~ms level (as low as ¼ ms) with linear acceleration at the step level while seamlessly joining segments together into a larger jerk-controlled motion curve. IOW, linear interpolation of a jerk-controlled motion curve with no step-level jitter.

-Rob

**Comment by slootmat** [comment]
Hi Rob,

I appreciate the broader context, and have already become familiar with
that as a result of poring over the G2 source, with particular focus on the
execution path that flows from the "_parse_gcode_block()"  all the way to
"_load_block()".

What I am almost clear about is the mechanism through which each motors's
steps are played out in a given segment. Please let me know whether my
understanding is captured in the below oversimplified use case.

For simplicity, suppose we eliminate( cancel out) the DDA_SUBSTEPS scale
factor from the algorithm (since it is contained in both "ticks_x_substeps"
and  "substep_increment"), and just look at the relationship between  these
two terms for one motor's "step_count" for one segment's "dda_ticks".

Suppose the total steps for a segment are 100   [==dda_ticks, right?] and
one motor's step_count is assigned 50.

a. Although I do not see in the source code where the accumulator is
initialized to the full negative count of steps, my example assumes the
accumulator is initialized to -100 before the first firing of the interrupt.
b. Out of 100 firings of the interrupt, to play out the segment's duration,
I would expect the accumulator to have 50 zero crossings in a even toggling
fashion, as modeled below:

     Init: Accumulator = -dda_ticks '' //== -100
    Interrupt activity:

    Interrupt entry:         accumulator += step_count      accumulator  -=
dda_ticks     motor step pin
     ------------                 ------------------------------------
----------------------------------      -------------------
       0                           -50
          N/A                                      0
       1                             0
           -100                                     1
       2                           -50
           N/A                                     0
       3                             0
           -100                                     1
       4                           -50
           N/A                                     0
        .                             .
                .                                         .
        .                             .
                .                                         .
        .                             .
                .                                         .
      98                           -50
          N/A                                     0
      99                             0
           -100                                    1


     Does that cover the essence of the algorithm, albeit leaving out the
scale factor?


Best,
Sam

**Comment by giseburt** [comment]
Essentially, yes. You chose a somewhat troublesome example, however, as the
step rate must be at most ⅓ the DDA rate.

So let’s say instead that over 100 dda ticks we want 10.1 steps.

We have dda_downcount set to 100, accumulator set to -1000 (our zero
accumulated sub-steps value), our increment set to 101=(10.1/100)*1000, and
the step pin set to 0 (inactive).

dda_downcount | accumulator | step pin
100 | -1000 | 0
99 | -899 | 0
98 | -798 | 0
...
91 | -91 | 0
90 | 10 → -990 | 1
89 | -889 | 0
88 | -788 | 0
...
0 | -900 | 0

Since we started at 0 steps and wanted to take 10.1 steps, ending up with
0.1=-1000+(0.1*1000) is correct.

Note that when we reverse directions we invert the accumulator within its
range, so if we reverse from here we would set the accumulator to -100,
meaning that we have already taken 0.9 of a step.

Does that make sense?

Ps the latest stepper code is here:
https://github.com/synthetos/g2/blob/dev-168-gquintic/g2core/stepper.cpp

-Rob

**Comment by slootmat** [comment]
Hi Rob,
Your explanation and example do make sense. I see it now, and I appreciate
the greater clarity in comments and code the latest stepper source you
provided. In particular, I see in the stepper_init function the explicit
initialization of the accumulators to the -STEP_DDA value whereas, in the
master branch, they are initialized to zero, and they only become negative
in the first entry t the -= decrement action in the interrupt. I do not see
anywhere in the master code branch where the accumulators start out before
the interrupt is triggered, with the large negative value.
================================
 master branch:
void stepper_reset()
{
    dda_timer.stop();                                   // stop all movement
    st_run.dda_ticks_downcount = 0;                     // signal the
runtime is not busy
    st_run.dwell_ticks_downcount = 0;
    st_pre.buffer_state = PREP_BUFFER_OWNED_BY_EXEC;    // set to EXEC or
it won't restart

    for (uint8_t motor=0; motor<MOTORS; motor++) {
        st_pre.mot[motor].prev_direction = STEP_INITIAL_DIRECTION;
        st_pre.mot[motor].direction = STEP_INITIAL_DIRECTION;
        st_run.mot[motor].substep_accumulator = 0;      // will become max
negative during per-motor setup;
        st_pre.mot[motor].corrected_steps = 0;          // diagnostic only
- no action effect
    }
    mp_set_steps_to_runtime_position();                 // reset encoder to
agree with the above
}
===========================================

The only non zero value they can receive before the interrupt is triggered
is a correction factor performed in st_prep_line(), and that cannot be the
same thing. I'm still puzzled over that.
===========================================
stat_t st_prep_line(float travel_steps[], float following_error[], float
segment_time)
{
.
.
.
        // Detect segment time changes and setup the accumulator correction
factor and flag.
        // Putting this here computes the correct factor even if the motor
was dormant for some number
        // of previous moves. Correction is computed based on the last
segment time actually used.

        if (fabs(segment_time - st_pre.mot[motor].prev_segment_time) >
0.0000001) { // highly tuned FP != compare
            if (fp_NOT_ZERO(st_pre.mot[motor].prev_segment_time)) {
         // special case to skip first move
                st_pre.mot[motor].accumulator_correction_flag = true;
                st_pre.mot[motor].accumulator_correction = segment_time /
st_pre.mot[motor].prev_segment_time;
            }
            st_pre.mot[motor].prev_segment_time = segment_time;
        }
.
.
.
}

Again, thank you very much for your support!

Best,

Sam

**Comment by slootmat** [comment]
Hi Justin,

I'm looking at the "back planning" methodology as deployed and described in
comments in the main branch.

1. Please confirm or correct my understanding:
    At "steady state"--when the planning queue fully populated (48
buffers), all entries ("blocks") are subject to being iteratively
re-planned/updated with each newly added "Move" block.

2. If my understanding is correct:
   a. Does the number of entries (48) represent a "sweet spot" in the
back-planning method, or would a larger population of entries produce even
smoother results?
   b. Suppose the Gcode program in it's entirety were not received in a
stream of packets, but could be resident in RAM on the embedded MCU such
that the size of the planning queue was the number all the fully parsed,
ready-to-plan blocks.
           i. Would the intention of back-planning be equally accomplished
by a single pass through the entire planning queue, or,
           ii. Would proper back-planning still need to involve some moving
window or modulo of say 48 blocks, to "march" through the entire queue? I'm
guessing this would need to be done.

Thanks,

Sam

**Comment by justinclift** [comment]
@giseburt Yours. :smile:

**Pull request closed without merging**
