### PR TITLE
Fix coolant-init (partly fixes #336)

### LINKED ISSUE #336: init: coolant not initialized, no early I/O-init
There are two issues with I/O-initialization:

1. **Coolant:** The coolant is not initialized. So, when setting the coolant to low-active, the coolant is on at power-on.

2. **late I/O-init:** The I/Os  are initialized **after** waiting 400ms for USB. So, for default-low-outputs, this results in a power-on-spike of ~0.4s. It would be better to **first** init the I/Os ("early I/O-preinit") to make this spike as short as possible, and then wait for USB.

Fixes:

1. Coolant: Add the following lines to main.cpp:
```
  #include "spindle.h"
+ #include "coolant.h"
  #include "temperature.h"

  ...

  void application_init_machine(void)
  {
      ...
      spindle_reset();
+     coolant_init();
+     coolant_reset();
      temperature_init();
```

2. early I/O-init: Initialize all I/Os directly after power-on, by moving some init-function-calls from
application_init_machine() and application_init_startup() to an earlier location. **I don't know the code in full detail, so I don't know if this has any side-effects, so some core-developer should check before merging.** My suggestion for main.cpp:
```
+ void application_init_io_early(void)
+ {
+     config_init();
+     gpio_init();
+     gpio_reset();
+     spindle_init();
+     spindle_reset();
+     coolant_init();
+     coolant_reset();
+ }

+ }
  void setup(void)
  {
      // application setup
      application_init_services();
+     // early I/O-init
+     application_init_io_early();
+
      while (SysTickTimer_getValue() < 400);  // delay 400 ms for USB to come up

      application_init_machine();
      application_init_startup();
  }
```

### PR DESCRIPTION
**Pull request by rkoe**
The coolant-I/Os are currently not initialized. Fix this by adding coolant_init/coolant_reset to the initialization-functions. Fixes #336 part 1.

### CODE REVIEW

**Comment by justinclift** [comment]
Oops, this was done against the `master` branch.  Would you ok to update it for the `edge` branch, which is what we do development against?

**Comment by justinclift** [comment]
Actually, I might be able to press buttons here and get it working.  1 min... :smile:

...

Nope,  tried that and it just went weird.  Sorry @rkoe, I probably should have mentioned that first.

Um... you might need to close this issue and open a new one with the PR against `edge`.  GitHub doesn't always seem to go well with the branch names getting changed inside a PR. 😇

**Comment by justinclift** [comment]
As a thought, this doc might help too: https://github.com/synthetos/g2/wiki/Development-Process

It gives some guidelines useful when doing code stuff with g2core, and also says how to run the regression tests (important). :smile:

**Comment by rkoe** [comment]
Ok, I've closed it and added a new PR. If this doesn't work, then you have to integrate the 3 lines of code yourself to fix the bug.

Sorry, but I don't use git daily, and so I'm not a git expert -- which you obviously have to be for your workflow. 5% bug fix, 95% workflow overhead. I don't like that. Git/github should make things easier, but it seems to make it much more complicated... :(

**Comment by justinclift** [comment]
Ahhh yeah.  I remember really hating git when first having to use it.  Complete PITA.

Once you get the hang of it, it's pretty decent.  But for occasional use, where there's no strong driver to really come to grips with it... that's probably not going to be great fun.

Looking at our [development process wiki page](https://github.com/synthetos/g2/wiki/Development-Process), we could probably put the exact command line instructions in there for people to use.  That should reduce the problem's that crop up when people start the development process using the `master` instead of `edge` branch.

**Comment by justinclift** [comment]
As an extra thought, if you're familiar with using IRC or Gitter, I can walk you through the git bits needed to make PR's for this repo.  eg hands on interactive walk though

**Pull request closed without merging**
