### PR TITLE
Update A, B, C axes radius defaults to use motors 4, 5, & 6

### PR DESCRIPTION
**Pull request by justinclift**
As per issue #134

### CODE REVIEW

**Comment by justinclift** [comment]
Note that in defines just a few lines down (eg `A_VELOCITY MAX`), there are further references to M1:

```
#define A_VELOCITY_MAX              ((X_VELOCITY_MAX/M1_TRAVEL_PER_REV)*360) // set to the same speed as X axis
```

That usage of M1 seems correct though, as it's looking to set the default A velocity to match the X axis specifically.  Changing that to use M4 wouldn't make sense, as it would need `X_VELOCITY_MAX` changed too (to match)... and that's the definition being created on this line. :wink:

**Comment by aldenhart** [comment]
This was set up to make the rotary axes move at the same speeds as the linear axes for testing purposes. Once the UVW code is pulled in a user can have 6 actual linear axes, so this will be less valuable. We should probably set it up for a common use case for 4 and 5 axis machines.

**Comment by justinclift** [comment]
> Once the UVW code is pulled in a user can have 6 actual linear axes, so this will be less valuable.

k.  Any kind of roughly expected ETA for the UVW code?  Just thinking that since this one + #134 are kind of simple, it might make sense to get them merged sooner rather than later.

Note though that could just be me being impatient. :wink:

> We should probably set it up for a common use case for 4 and 5 axis machines.

Definitely. :smile:

**Comment by aldenhart** [comment]
I pushed a couple of commits on this over the weekend and ran the regressions on it. It should go out in the next day or 2. Need to do some final steps.

**Comment by justinclift** [comment]
> Once the UVW code is pulled in a user can have 6 actual linear axes, so this will be less valuable.

Now the UVW code is pulled in, what's the optimal thing to do with this PR?  Just close it (and Issue #134) then take a different approach? :smile:

**Comment by aldenhart** [comment]
I think it still makes sense to have a default mapping. I suspect the case of a 4th axis is more common that 4 or more linear axes. I think we should still consider these changes. We probably also need associated documentation somewhere on the wiki about these options.

**Review by giseburt — APPROVED** [review]
Looks good!

**Pull request merged**
