### PR TITLE
merged in omc SD card functionality

### PR DESCRIPTION
**Pull request by mikest**
dev-omc-issue2 + SD card support.

### CODE REVIEW

**Comment by justinclift** [comment]
Re-opening, accidentally closed this. :wink:

**Comment by mikest** [comment]
this was filed half a decade ago. i think you can safely close it ;)

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by ril3y** [comment]
Hi Mike!

**Comment by mikest** [comment]
@ril3y *waves* :)

**Pull request closed without merging**
