### PR TITLE
Update DueFromOSX.sh to auto-locate bossac and related utils

### PR DESCRIPTION
**Pull request by justinclift**
It could still be improved significantly, but it seems a lot
better than it was.  Also won't silently overwrite an existing
(downloaded) .bin file in the same directory any more.

### CODE REVIEW

**Comment by justinclift** [comment]
As a newbie to ARM and flashing things to the Due, it was a bit
disconcerting to have the script error out with missing utils.  It
turns out the Arduino IDE have moved their default location since
the wiki instructions were last tweaked.

So, made the script a bit more rugged, to try and autodetect the
utils in their new location - $HOME/Library/Arduino15/packages/.

**Comment by justinclift** [comment]
Hmmm, hold off on merging this just yet.  Current state of this patch allows the script to work with Arduino IDE 1.6.x, but it breaks working with earlier versions.  I'll update the script so it works with both. :smile:

**Comment by justinclift** [comment]
Should be good now.  Tested with Arduino IDE 1.5.7 and 1.6.8 on OSX 10.9.5. :smile:

**Comment by FutureSharks** [comment]
I just ran into the issues fixed in this PR:
```
+ arm-none-eabi-objcopy -O binary TinyG2.elf TinyG2.bin
./DueFromOSX.sh: line 59: arm-none-eabi-objcopy: command not found

./DueFromOSX.sh: line 73: /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/bossac: No such file or directory
```

One year and this still hasn't been merged? Is there some problem with this PR?

**Comment by knollja** [comment]
Please could someone check this in?  Please?  It's been almost two years, and the current checked script does not work.

**Comment by benlaurie** [comment]
Until this is committed, the easy way is to go here:

https://raw.githubusercontent.com/synthetos/g2/2337102e71de9d9eb29fea6405365915dc2475a2/Resources/TinyG2-OSX-Programmer/DueFromOSX.sh

Then save the page on top of the existing script.

**Comment by ril3y** [comment]
I also think you guys should check this out.  Might help
https://github.com/synthetos/g2/wiki/Flashing-with-Node-SAM-Ba-Utility-in-OSX

**Comment by justinclift** [comment]
@ril3y Weirdly, although this is merged I don't seem to be appearing in the list of contributors to the repo:

&nbsp; &nbsp; https://github.com/synthetos/g2/graphs/contributors

Any idea why?

**Pull request merged**
