### PR TITLE
Tomash cnc test

### PR DESCRIPTION
**Pull request by tomashx**
My first try to adapt G2 to my CNC machine. I'm sorry if I'm something doing wrong...

### CODE REVIEW

**Comment by ril3y** [comment]
Hey thanks for the pull request.  After looking at this I am going to have to close this.  Let me explain.
It looks like you (or perhaps your editor) did not edit the files in place but moved or recreated them.  If you look at the diff's you can see that the WHOLE file has been changed.  Which is obviously not what happened.  Also for your settings, you look to also be changing other files that are not really needed to create a settings file.  If you would like to close this pull request and only submit your tormach_setting.h (or whatever the file was) we can gladly merge that.

Right now, no one can tell what you really changed due to what I explained above.

Also if you need to change files for YOUR setup (not likely IMO) then you can always create a fork and maintain it.

**Comment by ril3y** [comment]
Damn mis-click sorry.

**Comment by MitchBradley** [comment]
My first guess would be line ending differences.  It can be tricky to set up git to handle the line ending differences between Linux/Mac and Windows.  Another common source of spurious diffs is the tendency for some editors to auto-format code using different conventions than what is used in the repo.

**Comment by tomashx** [comment]
> Hey thanks for the pull request. After looking at this I am going to have to close this. Let me explain. It looks like you (or perhaps your editor) did not edit the files in place but moved or recreated them. If you look at the diff's you can see that the WHOLE file has been changed. Which is obviously not what happened. Also for your settings, you look to also be changing other files that are not really needed to create a settings file. If you would like to close this pull request and only submit your tormach_setting.h (or whatever the file was) we can gladly merge that.
> 
> Right now, no one can tell what you really changed due to what I explained above.
> 
> Also if you need to change files for YOUR setup (not likely IMO) then you can always create a fork and maintain it.

Thanks for your answer! This commits are for my personal use only...for now. I'm trying to figure it out how is everything connected in code. I need to learn better a github (first time use) and how to use it. I thought that commits will be done in my repo. Sorry for inconvenience. I will ask my friend to show me how to use github properly. 
Also I have a trouble to setup edge-preview with gShield. Laser tool error coming up all times. I have tried to remove everything from pressurizer commit as somebody suggested, after that i was able to build solution, but motors  refuse to move with this build.

**Pull request closed without merging**
