### PR TITLE
Turn on motors that don't move if they have MOTOR_POWERED_IN_CYCLE

### PR DESCRIPTION
**Pull request by lutorm**
Without these changes, a single-axis move would only turn on the motor that's moving, even if other motors have power mode MOTOR_POWERED_IN_CYCLE.

Most changes are actually only whitespace indentation changes because the indentation in this code did not match the structure, so it was hard to read.

### CODE REVIEW

**Comment by lutorm** [comment]
Although I have to admit I don't understand why motors are also powered  if they have zero steps but set to MOTOR_POWERED_ONLY_WHEN_MOVING. I didn't want to change that, but it seems if they have zero steps they aren't moving and should not be powered on?

**Comment by aldenhart** [comment]
Thank you very much for both your PR's. I'm on travel but should be able to look this over later in the week.

**Comment by anthonywebb** [comment]
@aldenhart I would love to see these pull requests merged if they are acceptable to you.

**Comment by ril3y** [comment]
Hey guys, alden was on vacation for the holidays and should be getting back
up to speed here in the next week or so.  I wanted everyone to know we
appreciate the pull requests!  Alden is the lead dev so I could merge them
but he is the guy that needs to "sign off" on it :)

just a quick update!

ril3y

**Comment by giseburt** [comment]
This looks good to me, but before merging I'd like @aldenhart to look it over as well. This is a very vital area of the code, so we often double-check changes here.

**Comment by lutorm** [comment]
Understandable. Sorry for all the indentation changes, by the way. Maybe it would have been better to isolate the code changes.

**Comment by giseburt** [comment]
About the indentation, no problem. Once we're at a clean breaking point, I'll do a repo-wide tabs->spaces indention normalization, but since it muddies up the history, I don't want to do it quite yet.

Also, thanks for the work on this. It's very much appreciated.

**Comment by lutorm** [comment]
Is this getting included in edge-100, too?

**Comment by aldenhart** [comment]
There was a good deal of refactoring in the stepper section for edge-100. We are including fixes for motor power timeout. This work is underway now. You can see progress of issues by looking at he waffle: https://waffle.io/synthetos/g2

**Comment by aldenhart** [comment]
This behaviour is fixed in current edge. Closing PR - no need to merge it in.

**Pull request closed without merging**
