### PR TITLE
Add licence, as per #176

### PR DESCRIPTION
**Pull request by justinclift**
This file is the text from G2core-License on the wiki, with whitespace
added between sections for better visual display as text.

  https://github.com/synthetos/g2/wiki/G2core-License

### CODE REVIEW

**Review by giseburt — APPROVED** [review]
👍

**Comment by justinclift** [comment]
With the approval from @giseburt, does that mean I'm ok to hit the merge button on this, or are we waiting for futher review?

Note - Just asking because I'm unsure of the accepted process.  The [dev process wiki page](https://github.com/synthetos/g2/wiki/Development-Process) doesn't seem to cover this aspect of PRs (yet). :wink:

**Comment by giseburt** [comment]
Well in this case, as long as it will merge cleanly, then yes. I’m not sure
why the dev process doesn’t cover reviews.

In general, if a review is requested then that reviewer should approve
before it goes through. In this case that would mean Alden has to review
and approve also, since a review was also requested from him.

Thank you Justin!

**Comment by justinclift** [comment]
Thanks @giseburt.  Figured it better to ask rather than jump the gun. :smile:

**Pull request merged**
