### PR TITLE
Adding inch versions of VCarve post processors.

### PR DESCRIPTION
**Pull request by mhlong10**

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @mhlong10.  I'm happy to merge this if you reckon it's ready? :smile:

**Comment by mhlong10** [comment]
I've quickly tested all files and quadruple checked the changes.  If people want they can diff between the mm and inch versions to see what was changed.

This should be good to go.

**Comment by justinclift** [comment]
No worries.  It seems like you accidentally added the in-development laser raster code to this same branch though, so I can't merge this just yet.

Ping me in chat later on, and I can walk you through the git branching thing if that's useful. :smile:

**Comment by mhlong10** [comment]
I've removed the last commit.  Back to a clean PR.  Sorry about that.

**Comment by justinclift** [comment]
It's all good, thanks @mhlong10. :smile:

**Pull request merged**
